version: "3.1"

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbit"
    ports:
    - "15672:15672"
    - "5672:5672"
    labels:
      NAME: "rabbitmq"

  ci-droid-rest:
    image: "ci-droid-rest:latest"
    ports:
    - "8080:8080"

  ci-droid-tasks-consumer_1:
    image: "ci-droid-tasks-consumer:latest"

  ci-droid-tasks-consumer_2:
    image: "ci-droid-tasks-consumer:latest"