FROM openjdk:8-jre

# Create user and workdir for running application
ENV USER_HOME /home/ci-droid
ARG user=ci-droid
ARG group=ci-droid
ARG uid=1000
ARG gid=1000

ARG APPLI_NAME

RUN groupadd -g ${gid} ${group} \
    && useradd -d "${USER_HOME}" -u ${uid} -g ${gid} -m -s /bin/bash ${user}

WORKDIR $USER_HOME

COPY $APPLI_NAME.jar ./application.jar
COPY $APPLI_NAME-config.yml ./application.yml

RUN chown ci-droid:ci-droid ./application.jar && \
    chown ci-droid:ci-droid ./application.yml

COPY entrypoint.sh ./
RUN chown ci-droid:ci-droid ./entrypoint.sh && \
    chmod 755 ./entrypoint.sh


#switching to specific user
USER ci-droid

ENTRYPOINT ["./entrypoint.sh"]